<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => 'Применить',
    'Cancel' => 'Отмена',
    'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>' => 'Перетащите файлы или <span class="filepond--label-action"> Обзор </span>',
    'Edit image' => 'Редактировать изображение',
    'Expects {allButLastType} or {lastType}' => 'Ожидает {allButLastType} или {lastType}',
    'File is too large' => 'Файл слишком большой',
    'File is too small' => 'Файл слишком маленький',
    'File type not allowed' => 'Тип файла не разрешен',
    'Free' => 'Свободно',
    'Maximum file size is {filesize}' => 'Максимальный размер файла {filesize}',
    'Maximum total file size is {filesize}' => 'Максимальный общий размер файла {filesize}',
    'Maximum total size exceeded' => 'Превышен максимальный общий размер',
    'Minimum file size is {filesize}' => 'Минимальный размер файла {filesize}',
    'Reset' => 'Сбросить',
    'The uploaded file is not a valid FilePond payload.' => 'Загруженный файл не является допустимыми данными FilePond.',
    'Zoom in' => 'Увеличить',
    'Zoom out' => 'Уменьшить',
];
