<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => 'Aplicar',
    'Cancel' => 'Cancelar',
    'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>' => 'Arrastra y suelta tus archivos o <span class="filepond--label-action"> Navega </span>',
    'Edit image' => 'Editar imagen',
    'Expects {allButLastType} or {lastType}' => 'Espera {allButLastType} o {lastType}',
    'File is too large' => 'El archivo es demasiado grande',
    'File is too small' => 'El archivo es demasiado pequeño',
    'File type not allowed' => 'Tipo de archivo no permitido',
    'Free' => 'Libre',
    'Maximum file size is {filesize}' => 'El tamaño máximo del archivo es {filesize}',
    'Maximum total file size is {filesize}' => 'El tamaño total máximo del archivo es {filesize}',
    'Maximum total size exceeded' => 'Se ha excedido el tamaño total máximo',
    'Minimum file size is {filesize}' => 'El tamaño mínimo del archivo es {filesize}',
    'Reset' => 'Restablecer',
    'The uploaded file is not a valid FilePond payload.' => 'El archivo subido no es una carga útil válida de FilePond.',
    'Zoom in' => 'Acercar',
    'Zoom out' => 'Alejar',
];
