<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>' => 'Przeciągnij i upuść pliki lub <span class="filepond--label-action"> Przeglądaj </span>',
    'Expects {allButLastType} or {lastType}' => 'Oczekuje {allButLastType} lub {lastType}',
    'File is too large' => 'Rozmiar pliku jest za duży',
    'File type not allowed' => 'Niedozwolony typ pliku',
    'Maximum file size is {filesize}' => 'Maksymalny rozmiar pliku to {filesize}',
    'Maximum total file size is {filesize}' => 'Maksymalny całkowity rozmiar plików to {filesize}',
    'Maximum total size exceeded' => 'Przekroczono maksymalny łączny rozmiar plików',
];
