<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply' => 'Aplicar',
    'Cancel' => 'Cancelar',
    'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>' => 'Arraste e solte seus arquivos ou <span class="filepond--label-action"> Navegar </span>',
    'Edit image' => 'Editar imagem',
    'Expects {allButLastType} or {lastType}' => 'Espera {allButLastType} ou {lastType}',
    'File is too large' => 'O arquivo é muito grande',
    'File is too small' => 'O arquivo é muito pequeno',
    'File type not allowed' => 'Tipo de arquivo não permitido',
    'Free' => 'Livre',
    'Maximum file size is {filesize}' => 'O tamanho máximo do arquivo é {filesize}',
    'Maximum total file size is {filesize}' => 'O tamanho total máximo do arquivo é {filesize}',
    'Maximum total size exceeded' => 'Tamanho total máximo excedido',
    'Minimum file size is {filesize}' => 'O tamanho mínimo do arquivo é {filesize}',
    'Reset' => 'Redefinir',
    'The uploaded file is not a valid FilePond payload.' => 'O arquivo enviado não é uma carga útil válida do FilePond.',
    'Zoom in' => 'Ampliar',
    'Zoom out' => 'Reduzir',
];
