<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>' => 'Քաշեք և թողեք ձեր ֆայլերը կամ <span class="filepond--label-action"> Ընտրեք </span>',
    'Expects {allButLastType} or {lastType}' => 'Ակնկալվում է {allButLastType} կամ {lastType}',
    'File is too large' => 'Ֆայլը չափազանց մեծ է',
    'File type not allowed' => 'Ֆայլի տեսակը չի թույլատրվում',
    'Maximum file size is {filesize}' => 'Ֆայլի առավելագույն չափը {filesize} է',
    'Maximum total file size is {filesize}' => 'Ֆայլի առավելագույն ընդհանուր չափը {filesize} է',
    'Maximum total size exceeded' => 'Առավելագույն ընդհանուր չափը գերազանցվել է',
];