<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>' => '拖放文件或<span class="filepond--label-action">浏览</span>',
    'Expects {allButLastType} or {lastType}' => '期望{allButLastType}或{lastType}',
    'File is too large' => '文件太大',
    'File type not allowed' => '文件类型不允许',
    'Maximum file size is {filesize}' => '文件大小最大为{filesize}',
    'Maximum total file size is {filesize}' => '总文件大小最大为{filesize}',
    'Maximum total size exceeded' => '超出最大总大小',
];
